#!/bin/bash
cd /media/matt/4a*/movies
mkdir reencode
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./0-9/101 Dalmations Live Action.mpg" -o "/reencode/./0-9/101 Dalmations Live Action.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./0-9/300.mpg" -o "/reencode/./0-9/300.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./0-9/310.mpg" -o "/reencode/./0-9/310.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./0-9/6 Days 7 Nights.mpg" -o "/reencode/./0-9/6 Days 7 Nights.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./C/Chronicles of Narnia 1.mpg" -o "/reencode/./C/Chronicles of Narnia 1.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./C/Chronicles of Riddick.mpg" -o "/reencode/./C/Chronicles of Riddick.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/Jersey Girl.mpg" -o "/reencode/./J/Jersey Girl.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/Jesse James-Assination of.mpg" -o "/reencode/./J/Jesse James-Assination of.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/Jesus.mpg" -o "/reencode/./J/Jesus.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/John Dies at the End.mpg" -o "/reencode/./J/John Dies at the End.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/Joseph.mpg" -o "/reencode/./J/Joseph.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/Journey to the Center of the Earth.mpg" -o "/reencode/./J/Journey to the Center of the Earth.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/Julie and Julia.mpg" -o "/reencode/./J/Julie and Julia.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/Juno.mpg" -o "/reencode/./J/Juno.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/Just Go With It.mpg" -o "/reencode/./J/Just Go With It.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/Just Like Heaven.mpg" -o "/reencode/./J/Just Like Heaven.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./J/Just My Luck.mpg" -o "/reencode/./J/Just My Luck.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Kangaroo Jack.mpg" -o "/reencode/./K/Kangaroo Jack.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Karate Kid.mpg" -o "/reencode/./K/Karate Kid.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Kicking and Screaming.mpg" -o "/reencode/./K/Kicking and Screaming.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Kids Are All Right.mpg" -o "/reencode/./K/Kids Are All Right.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Kill Bill Vol 1.mpg" -o "/reencode/./K/Kill Bill Vol 1.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Kill Bill Vol 2.mpg" -o "/reencode/./K/Kill Bill Vol 2.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Killers.mpg" -o "/reencode/./K/Killers.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/King and I.mpg" -o "/reencode/./K/King and I.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/King Kong.mp4" -o "/reencode/./K/King Kong.mp4"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Kingdom of Heaven.mpg" -o "/reencode/./K/Kingdom of Heaven.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Kingpin.mpg" -o "/reencode/./K/Kingpin.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Knight and Day.mpg" -o "/reencode/./K/Knight and Day.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Knights Tale.mpg" -o "/reencode/./K/Knights Tale.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Knocked Up.mpg" -o "/reencode/./K/Knocked Up.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Krays Documentary 1.mpg" -o "/reencode/./K/Krays Documentary 1.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Krays Documentary 2.mpg" -o "/reencode/./K/Krays Documentary 2.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./K/Kung Fu Panda.mpg" -o "/reencode/./K/Kung Fu Panda.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Last Man on Earth.mpg" -o "/reencode/./L/Last Man on Earth.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Last Man Standing.mpg" -o "/reencode/./L/Last Man Standing.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Laws of Attraction.mpg" -o "/reencode/./L/Laws of Attraction.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Legally Blonde.mpg" -o "/reencode/./L/Legally Blonde.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Legion.mpg" -o "/reencode/./L/Legion.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Lennon Legend.mpg" -o "/reencode/./L/Lennon Legend.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Les Revenants.mpg" -o "/reencode/./L/Les Revenants.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Letters to Juliette.mpg" -o "/reencode/./L/Letters to Juliette.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Life as a House.mpg" -o "/reencode/./L/Life as a House.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Life as We Know It.mpg" -o "/reencode/./L/Life as We Know It.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Limitless.mpg" -o "/reencode/./L/Limitless.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Little Foeckers.mpg" -o "/reencode/./L/Little Foeckers.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Little Manhattan.mpg" -o "/reencode/./L/Little Manhattan.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Little Princess.mpg" -o "/reencode/./L/Little Princess.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Little Rascals.mpg" -o "/reencode/./L/Little Rascals.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Lizzie McGuire Movie.mpg" -o "/reencode/./L/Lizzie McGuire Movie.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Lost in Translation.mpg" -o "/reencode/./L/Lost in Translation.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Love and Other Drugs.mpg" -o "/reencode/./L/Love and Other Drugs.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Love Happens.mpg" -o "/reencode/./L/Love Happens.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Lucky Number Sleven.mpg" -o "/reencode/./L/Lucky Number Sleven.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./L/Lucky You.mpg" -o "/reencode/./L/Lucky You.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/M.mpg" -o "/reencode/./M/M.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/MacGrubber.mpg" -o "/reencode/./M/MacGrubber.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Machete.mpg" -o "/reencode/./M/Machete.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Machinist.mpg" -o "/reencode/./M/Machinist.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Maiden Heist.mpg" -o "/reencode/./M/Maiden Heist.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Maltese Falcon.mpg" -o "/reencode/./M/Maltese Falcon.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Man in the Iron Mask.mpg" -o "/reencode/./M/Man in the Iron Mask.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Man on Fire.mpg" -o "/reencode/./M/Man on Fire.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Man Who Wasn't There.mpg" -o "/reencode/./M/Man Who Wasn't There.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Marie Antoinette.mpg" -o "/reencode/./M/Marie Antoinette.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Marley and Me.mpg" -o "/reencode/./M/Marley and Me.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Match Point.mpg" -o "/reencode/./M/Match Point.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Material Girls.mpg" -o "/reencode/./M/Material Girls.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mean Girls.mpg" -o "/reencode/./M/Mean Girls.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mechanic.mpg" -o "/reencode/./M/Mechanic.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Meet the Foeckers.mpg" -o "/reencode/./M/Meet the Foeckers.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Melinda and Melinda.mpg" -o "/reencode/./M/Melinda and Melinda.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Memphis Belle.mpg" -o "/reencode/./M/Memphis Belle.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Men Who Stare at Goats.mpg" -o "/reencode/./M/Men Who Stare at Goats.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Messengers 2 the Scarecrow.mpg" -o "/reencode/./M/Messengers 2 the Scarecrow.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mexican.mpg" -o "/reencode/./M/Mexican.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Michael Clayton.mpg" -o "/reencode/./M/Michael Clayton.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mighty.mpg" -o "/reencode/./M/Mighty.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Million Dollar Baby.mpg" -o "/reencode/./M/Million Dollar Baby.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Ministers.mpg" -o "/reencode/./M/Ministers.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mirrors.mpg" -o "/reencode/./M/Mirrors.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Misconceptions.mpg" -o "/reencode/./M/Misconceptions.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Monster.mpg" -o "/reencode/./M/Monster.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Monsters Ball.mpg" -o "/reencode/./M/Monsters Ball.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Morning Glory.mpg" -o "/reencode/./M/Morning Glory.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Moscow Zero.mpg" -o "/reencode/./M/Moscow Zero.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Motherhood.mpg" -o "/reencode/./M/Motherhood.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Moulin Rouge.mpg" -o "/reencode/./M/Moulin Rouge.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mr and Mrs Smith.mpg" -o "/reencode/./M/Mr and Mrs Smith.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mr. Deeds.mpg" -o "/reencode/./M/Mr. Deeds.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mr. Mom.mpg" -o "/reencode/./M/Mr. Mom.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mulholland Falls.mpg" -o "/reencode/./M/Mulholland Falls.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mummy.mpg" -o "/reencode/./M/Mummy.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Munich.mpg" -o "/reencode/./M/Munich.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Murderous Intent.mpg" -o "/reencode/./M/Murderous Intent.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Music and Lyrics.mpg" -o "/reencode/./M/Music and Lyrics.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Must Love Dogs.mpg" -o "/reencode/./M/Must Love Dogs.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/My Big Fat Greek Wedding.mpg" -o "/reencode/./M/My Big Fat Greek Wedding.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mystery Train.mpg" -o "/reencode/./M/Mystery Train.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./M/Mystic River.mpg" -o "/reencode/./M/Mystic River.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./N/Natural Born Killeres.mpg" -o "/reencode/./N/Natural Born Killeres.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./N/New Daughter.mpg" -o "/reencode/./N/New Daughter.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./N/New York Minute.mpg" -o "/reencode/./N/New York Minute.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./N/Next Friday.mpg" -o "/reencode/./N/Next Friday.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./N/Nick and Noras Infinite Playlist.mpg" -o "/reencode/./N/Nick and Noras Infinite Playlist.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./N/Night Listener.mpg" -o "/reencode/./N/Night Listener.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./N/No Strings Attached.mpg" -o "/reencode/./N/No Strings Attached.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./N/Notebook.mpg" -o "/reencode/./N/Notebook.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./N/Notorious Bettie Paige.mpg" -o "/reencode/./N/Notorious Bettie Paige.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./N/Number 23.mpg" -o "/reencode/./N/Number 23.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./O/On Golden Pond.mpg" -o "/reencode/./O/On Golden Pond.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./O/Once Upon a Crime.mpg" -o "/reencode/./O/Once Upon a Crime.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./O/One Hour Photo.mpg" -o "/reencode/./O/One Hour Photo.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./O/Other.mpg" -o "/reencode/./O/Other.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./O/Outsiders.mpg" -o "/reencode/./O/Outsiders.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./O/Oxford Murders.mpg" -o "/reencode/./O/Oxford Murders.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Paper Heart.mpg" -o "/reencode/./P/Paper Heart.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Paranormal Activity 3.mpg" -o "/reencode/./P/Paranormal Activity 3.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Passengers.mpg" -o "/reencode/./P/Passengers.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Paul.mpg" -o "/reencode/./P/Paul.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Pay It Forward.mpg" -o "/reencode/./P/Pay It Forward.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Penelope.mpg" -o "/reencode/./P/Penelope.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Perfect Getaway.m4v" -o "/reencode/./P/Perfect Getaway.m4v"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Phantasm.mpg" -o "/reencode/./P/Phantasm.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Pink Panther - Steve Martin.mpg" -o "/reencode/./P/Pink Panther - Steve Martin.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Powderpuff Girls.mpg" -o "/reencode/./P/Powderpuff Girls.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Precious.mpg" -o "/reencode/./P/Precious.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Prince N Me.mpg" -o "/reencode/./P/Prince N Me.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Prince of Egypt.mpg" -o "/reencode/./P/Prince of Egypt.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Princess of Theives.mpg" -o "/reencode/./P/Princess of Theives.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Prom Night.mpg" -o "/reencode/./P/Prom Night.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Proof.mpg" -o "/reencode/./P/Proof.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Public Enemies.mpg" -o "/reencode/./P/Public Enemies.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./P/Punch Drunk Love.mpg" -o "/reencode/./P/Punch Drunk Love.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./Q/Quiz Show.mpg" -o "/reencode/./Q/Quiz Show.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Rachel Getting Married.mpg" -o "/reencode/./R/Rachel Getting Married.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Raise Your Voice.mpg" -o "/reencode/./R/Raise Your Voice.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Raw.mpg" -o "/reencode/./R/Raw.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Ray.mpg" -o "/reencode/./R/Ray.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Real Steel.mpg" -o "/reencode/./R/Real Steel.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Reality Bites.mpg" -o "/reencode/./R/Reality Bites.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Red Dawn.mpg" -o "/reencode/./R/Red Dawn.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Red.mpg" -o "/reencode/./R/Red.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Reign Over Me.mpg" -o "/reencode/./R/Reign Over Me.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Remember the Titans.mpg" -o "/reencode/./R/Remember the Titans.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Reno 911.mpg" -o "/reencode/./R/Reno 911.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Revolver.mpg" -o "/reencode/./R/Revolver.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Rhapsody in August.mpg" -o "/reencode/./R/Rhapsody in August.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Ring 2.mpg" -o "/reencode/./R/Ring 2.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Ring.mpg" -o "/reencode/./R/Ring.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Ringer.mpg" -o "/reencode/./R/Ringer.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Rio.mpg" -o "/reencode/./R/Rio.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Rise of the Planet of the Apes.mpg" -o "/reencode/./R/Rise of the Planet of the Apes.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Road to Perdition.mpg" -o "/reencode/./R/Road to Perdition.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Rookie.mpg" -o "/reencode/./R/Rookie.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Room 6.mpg" -o "/reencode/./R/Room 6.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Roommate.mpg" -o "/reencode/./R/Roommate.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Rumble Fish.mpg" -o "/reencode/./R/Rumble Fish.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Rumor Has It.mpg" -o "/reencode/./R/Rumor Has It.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Runaways.mpg" -o "/reencode/./R/Runaways.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Rundown.mpg" -o "/reencode/./R/Rundown.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/Running with Scissors.mpg" -o "/reencode/./R/Running with Scissors.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./R/RV.mpg" -o "/reencode/./R/RV.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/S Darko.mpg" -o "/reencode/./S/S Darko.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Saved.mpg" -o "/reencode/./S/Saved.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Saving Private Ryan.mpg" -o "/reencode/./S/Saving Private Ryan.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/School Of Rock.mpg" -o "/reencode/./S/School Of Rock.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Season Of The Witch.mpg" -o "/reencode/./S/Season Of The Witch.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Secret Life Of Bees.mpg" -o "/reencode/./S/Secret Life Of Bees.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Seeker.mpg" -o "/reencode/./S/Seeker.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Seitch.mpg" -o "/reencode/./S/Seitch.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Serendipity.mpg" -o "/reencode/./S/Serendipity.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Serious Moonlight.mpg" -o "/reencode/./S/Serious Moonlight.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Seven Samurai.mpg" -o "/reencode/./S/Seven Samurai.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Seventh Sign.mpg" -o "/reencode/./S/Seventh Sign.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Shaggy Dog.mpg" -o "/reencode/./S/Shaggy Dog.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Sherrybaby.mpg" -o "/reencode/./S/Sherrybaby.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Shes The Man.mpg" -o "/reencode/./S/Shes The Man.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Shogun Assassin.mpg" -o "/reencode/./S/Shogun Assassin.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Sideways.mpg" -o "/reencode/./S/Sideways.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Signs.mpg" -o "/reencode/./S/Signs.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Silencers.mpg" -o "/reencode/./S/Silencers.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Slapshot.mpg" -o "/reencode/./S/Slapshot.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Sleepers.mpg" -o "/reencode/./S/Sleepers.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Sleepless In Seattle.mpg" -o "/reencode/./S/Sleepless In Seattle.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Slingshot.mpg" -o "/reencode/./S/Slingshot.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Slumdog Millionaire.mpg" -o "/reencode/./S/Slumdog Millionaire.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Smokey And The Bandit.mpg" -o "/reencode/./S/Smokey And The Bandit.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Smokin Aces.mpg" -o "/reencode/./S/Smokin Aces.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Smother.mpg" -o "/reencode/./S/Smother.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Something Borrowed.mpg" -o "/reencode/./S/Something Borrowed.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Something Gotta Give.mpg" -o "/reencode/./S/Something Gotta Give.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Something To Talk About.mpg" -o "/reencode/./S/Something To Talk About.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Source Code.mpg" -o "/reencode/./S/Source Code.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Spanglish.mpg" -o "/reencode/./S/Spanglish.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Speed Racer.mpg" -o "/reencode/./S/Speed Racer.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Speed.mpg" -o "/reencode/./S/Speed.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Spiderwick.mpg" -o "/reencode/./S/Spiderwick.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Splice.mpg" -o "/reencode/./S/Splice.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Spongebob The Movie.mpg" -o "/reencode/./S/Spongebob The Movie.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Spy Next Door.mpg" -o "/reencode/./S/Spy Next Door.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Stardust.mpg" -o "/reencode/./S/Stardust.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Stargate Part1.mpg" -o "/reencode/./S/Stargate Part1.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Stargate Part2.mpg" -o "/reencode/./S/Stargate Part2.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Station Agent.mpg" -o "/reencode/./S/Station Agent.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Stealing Sinatra.mpg" -o "/reencode/./S/Stealing Sinatra.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Step Brothers.mpg" -o "/reencode/./S/Step Brothers.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Step Up.mpg" -o "/reencode/./S/Step Up.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Stepfather.mpg" -o "/reencode/./S/Stepfather.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Stepmom.mpg" -o "/reencode/./S/Stepmom.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Stomp The Yard.mpg" -o "/reencode/./S/Stomp The Yard.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Strange Brew.mpg" -o "/reencode/./S/Strange Brew.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Stuck On You.mpg" -o "/reencode/./S/Stuck On You.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Stuck.mpg" -o "/reencode/./S/Stuck.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Super Size Me.mpg" -o "/reencode/./S/Super Size Me.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Super.mpg" -o "/reencode/./S/Super.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Superstar.mpg" -o "/reencode/./S/Superstar.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Surfs Up.mpg" -o "/reencode/./S/Surfs Up.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Surrogates.mpg" -o "/reencode/./S/Surrogates.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Surveillance.mpg" -o "/reencode/./S/Surveillance.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Sweet November.mpg" -o "/reencode/./S/Sweet November.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./S/Sydney White.mpg" -o "/reencode/./S/Sydney White.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Take Me Home Tonight.mpg" -o "/reencode/./T/Take Me Home Tonight.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Taking Lives.mpg" -o "/reencode/./T/Taking Lives.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Talladega Nights.mpg" -o "/reencode/./T/Talladega Nights.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Tangled.mpg" -o "/reencode/./T/Tangled.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Taxi.mpg" -o "/reencode/./T/Taxi.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Tenure.mpg" -o "/reencode/./T/Tenure.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Terminal.mpg" -o "/reencode/./T/Terminal.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Texas Chainsaw Massacre.mpg" -o "/reencode/./T/Texas Chainsaw Massacre.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/The Tourist.mpg" -o "/reencode/./T/The Tourist.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Thelma And Louise.mpg" -o "/reencode/./T/Thelma And Louise.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/They.mpg" -o "/reencode/./T/They.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Thing.mpg" -o "/reencode/./T/Thing.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Three Burials.mpg" -o "/reencode/./T/Three Burials.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Tideland.mpg" -o "/reencode/./T/Tideland.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Time Travelers Wife.mpg" -o "/reencode/./T/Time Travelers Wife.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Tin Men.mpg" -o "/reencode/./T/Tin Men.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Tolkien Ntsc Scn.mpg" -o "/reencode/./T/Tolkien Ntsc Scn.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Transsiberian.mpg" -o "/reencode/./T/Transsiberian.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Trapped In Paradise.mpg" -o "/reencode/./T/Trapped In Paradise.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Traveler.mpg" -o "/reencode/./T/Traveler.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Tropic Thunder.mpg" -o "/reencode/./T/Tropic Thunder.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Troy.mpg" -o "/reencode/./T/Troy.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/True Grit.mpg" -o "/reencode/./T/True Grit.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Twelve.mpg" -o "/reencode/./T/Twelve.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Twister.mpg" -o "/reencode/./T/Twister.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./T/Two Weeks Notice.mpg" -o "/reencode/./T/Two Weeks Notice.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./U/Ugly.mpg" -o "/reencode/./U/Ugly.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./U/Unaccompanied Minors.mpg" -o "/reencode/./U/Unaccompanied Minors.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./U/Unbreakable.mpg" -o "/reencode/./U/Unbreakable.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./U/Under Wraps.mpg" -o "/reencode/./U/Under Wraps.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./U/Unforgettable.mpg" -o "/reencode/./U/Unforgettable.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./U/Unhappily Ever After.mpg" -o "/reencode/./U/Unhappily Ever After.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./U/Untouchables.mpg" -o "/reencode/./U/Untouchables.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./V/Vacancy.mpg" -o "/reencode/./V/Vacancy.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./V/Valentines Day.mpg" -o "/reencode/./V/Valentines Day.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./V/Valkyrie.mpg" -o "/reencode/./V/Valkyrie.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./V/Vantage Point.mpg" -o "/reencode/./V/Vantage Point.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./V/Village.mpg" -o "/reencode/./V/Village.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./V/Vow.mpg" -o "/reencode/./V/Vow.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Waiting For Guffman.mpg" -o "/reencode/./W/Waiting For Guffman.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Wanted.mpg" -o "/reencode/./W/Wanted.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/War Inc.mpg" -o "/reencode/./W/War Inc.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/We.mpg" -o "/reencode/./W/We.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Wedding Planner.mpg" -o "/reencode/./W/Wedding Planner.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Wedding Singer.mpg" -o "/reencode/./W/Wedding Singer.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Welcome To Mooseport169.mpg" -o "/reencode/./W/Welcome To Mooseport169.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Westworld.mpg" -o "/reencode/./W/Westworld.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/What To Expect When Youre Expecting.mpg" -o "/reencode/./W/What To Expect When Youre Expecting.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Whats Up Tiger Lily.mpg" -o "/reencode/./W/Whats Up Tiger Lily.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/When A Man Loves A Woman.mpg" -o "/reencode/./W/When A Man Loves A Woman.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/When In Rome.mpg" -o "/reencode/./W/When In Rome.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Whip It.mpg" -o "/reencode/./W/Whip It.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/White Chicks.mpg" -o "/reencode/./W/White Chicks.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Whiteout.mpg" -o "/reencode/./W/Whiteout.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Who Framed Roger Rabbit.mpg" -o "/reencode/./W/Who Framed Roger Rabbit.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Whole Nine Yards.mpg" -o "/reencode/./W/Whole Nine Yards.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Wicker Man.mpg" -o "/reencode/./W/Wicker Man.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Wild Child.mpg" -o "/reencode/./W/Wild Child.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Wild Hogs.mpg" -o "/reencode/./W/Wild Hogs.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Win A Date With Tad Hamilton.mpg" -o "/reencode/./W/Win A Date With Tad Hamilton.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Winters Bone.mpg" -o "/reencode/./W/Winters Bone.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/World Trade Center.mpg" -o "/reencode/./W/World Trade Center.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Worlds Fastest Indian.mpg" -o "/reencode/./W/Worlds Fastest Indian.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Worlds Greatest Dad.mpg" -o "/reencode/./W/Worlds Greatest Dad.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./W/Wrecked.mpg" -o "/reencode/./W/Wrecked.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./Y/Yes Man.mpg" -o "/reencode/./Y/Yes Man.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./Y/You Me And Dupree.mpg" -o "/reencode/./Y/You Me And Dupree.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./Y/Yours Mine and Ours.mpg" -o "/reencode/./Y/Yours Mine and Ours.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./Y/Youth In Revolt.mpg" -o "/reencode/./Y/Youth In Revolt.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./Y/Youve Got Mail.mpg" -o "/reencode/./Y/Youve Got Mail.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./Z/Zack and Miri Make a Porno.mpg" -o "/reencode/./Z/Zack and Miri Make a Porno.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./Z/Zombieland.mpg" -o "/reencode/./Z/Zombieland.mpg"
HandBrakeCLI --preset-import-file ~/matts.json -Z "matts" -i "./Z/Zoom.mpg" -o "/reencode/./Z/Zoom.mpg"
