#!/bin/bash
cd /media/matt/4a*/movies
mkdir reencode
ffmpeg -i "0-9/300.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/0-9/300.mpg"
ffmpeg -i "0-9/310.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/0-9/310.mpg"
ffmpeg -i "0-9/6 Days 7 Nights.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/0-9/6 Days 7 Nights.mpg"
ffmpeg -i "C/Chronicles of Narnia 1.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/C/Chronicles of Narnia 1.mpg"
ffmpeg -i "C/Chronicles of Riddick.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/C/Chronicles of Riddick.mpg"
ffmpeg -i "J/Jersey Girl.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/Jersey Girl.mpg"
ffmpeg -i "J/Jesse James-Assination of.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/Jesse James-Assination of.mpg"
ffmpeg -i "J/Jesus.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/Jesus.mpg"
ffmpeg -i "J/John Dies at the End.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/John Dies at the End.mpg"
ffmpeg -i "J/Joseph.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/Joseph.mpg"
ffmpeg -i "J/Journey to the Center of the Earth.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/Journey to the Center of the Earth.mpg"
ffmpeg -i "J/Julie and Julia.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/Julie and Julia.mpg"
ffmpeg -i "J/Juno.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/Juno.mpg"
ffmpeg -i "J/Just Go With It.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/Just Go With It.mpg"
ffmpeg -i "J/Just Like Heaven.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/Just Like Heaven.mpg"
ffmpeg -i "J/Just My Luck.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/J/Just My Luck.mpg"
ffmpeg -i "K/Kangaroo Jack.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Kangaroo Jack.mpg"
ffmpeg -i "K/Karate Kid.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Karate Kid.mpg"
ffmpeg -i "K/Kicking and Screaming.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Kicking and Screaming.mpg"
ffmpeg -i "K/Kids Are All Right.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Kids Are All Right.mpg"
ffmpeg -i "K/Kill Bill Vol 1.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Kill Bill Vol 1.mpg"
ffmpeg -i "K/Kill Bill Vol 2.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Kill Bill Vol 2.mpg"
ffmpeg -i "K/Killers.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Killers.mpg"
ffmpeg -i "K/King and I.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/King and I.mpg"
ffmpeg -i "K/King Kong.mp4"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/King Kong.mp4"
ffmpeg -i "K/Kingdom of Heaven.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Kingdom of Heaven.mpg"
ffmpeg -i "K/Kingpin.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Kingpin.mpg"
ffmpeg -i "K/Knight and Day.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Knight and Day.mpg"
ffmpeg -i "K/Knights Tale.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Knights Tale.mpg"
ffmpeg -i "K/Knocked Up.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Knocked Up.mpg"
ffmpeg -i "K/Krays Documentary 1.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Krays Documentary 1.mpg"
ffmpeg -i "K/Krays Documentary 2.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Krays Documentary 2.mpg"
ffmpeg -i "K/Kung Fu Panda.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/K/Kung Fu Panda.mpg"
ffmpeg -i "L/Last Man on Earth.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Last Man on Earth.mpg"
ffmpeg -i "L/Last Man Standing.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Last Man Standing.mpg"
ffmpeg -i "L/Laws of Attraction.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Laws of Attraction.mpg"
ffmpeg -i "L/Legally Blonde.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Legally Blonde.mpg"
ffmpeg -i "L/Legion.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Legion.mpg"
ffmpeg -i "L/Lennon Legend.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Lennon Legend.mpg"
ffmpeg -i "L/Les Revenants.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Les Revenants.mpg"
ffmpeg -i "L/Letters to Juliette.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Letters to Juliette.mpg"
ffmpeg -i "L/Life as a House.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Life as a House.mpg"
ffmpeg -i "L/Life as We Know It.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Life as We Know It.mpg"
ffmpeg -i "L/Limitless.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Limitless.mpg"
ffmpeg -i "L/Little Foeckers.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Little Foeckers.mpg"
ffmpeg -i "L/Little Manhattan.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Little Manhattan.mpg"
ffmpeg -i "L/Little Princess.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Little Princess.mpg"
ffmpeg -i "L/Little Rascals.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Little Rascals.mpg"
ffmpeg -i "L/Lizzie McGuire Movie.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Lizzie McGuire Movie.mpg"
ffmpeg -i "L/Lost in Translation.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Lost in Translation.mpg"
ffmpeg -i "L/Love and Other Drugs.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Love and Other Drugs.mpg"
ffmpeg -i "L/Love Happens.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Love Happens.mpg"
ffmpeg -i "L/Lucky Number Sleven.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Lucky Number Sleven.mpg"
ffmpeg -i "L/Lucky You.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/L/Lucky You.mpg"
ffmpeg -i "M/M.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/M.mpg"
ffmpeg -i "M/MacGrubber.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/MacGrubber.mpg"
ffmpeg -i "M/Machete.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Machete.mpg"
ffmpeg -i "M/Machinist.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Machinist.mpg"
ffmpeg -i "M/Maiden Heist.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Maiden Heist.mpg"
ffmpeg -i "M/Maltese Falcon.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Maltese Falcon.mpg"
ffmpeg -i "M/Man in the Iron Mask.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Man in the Iron Mask.mpg"
ffmpeg -i "M/Man on Fire.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Man on Fire.mpg"
ffmpeg -i "M/Man Who Wasn't There.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Man Who Wasn't There.mpg"
ffmpeg -i "M/Marie Antoinette.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Marie Antoinette.mpg"
ffmpeg -i "M/Marley and Me.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Marley and Me.mpg"
ffmpeg -i "M/Match Point.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Match Point.mpg"
ffmpeg -i "M/Material Girls.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Material Girls.mpg"
ffmpeg -i "M/Mean Girls.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mean Girls.mpg"
ffmpeg -i "M/Mechanic.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mechanic.mpg"
ffmpeg -i "M/Meet the Foeckers.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Meet the Foeckers.mpg"
ffmpeg -i "M/Melinda and Melinda.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Melinda and Melinda.mpg"
ffmpeg -i "M/Memphis Belle.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Memphis Belle.mpg"
ffmpeg -i "M/Men Who Stare at Goats.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Men Who Stare at Goats.mpg"
ffmpeg -i "M/Messengers 2 the Scarecrow.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Messengers 2 the Scarecrow.mpg"
ffmpeg -i "M/Mexican.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mexican.mpg"
ffmpeg -i "M/Michael Clayton.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Michael Clayton.mpg"
ffmpeg -i "M/Mighty.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mighty.mpg"
ffmpeg -i "M/Million Dollar Baby.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Million Dollar Baby.mpg"
ffmpeg -i "M/Ministers.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Ministers.mpg"
ffmpeg -i "M/Mirrors.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mirrors.mpg"
ffmpeg -i "M/Misconceptions.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Misconceptions.mpg"
ffmpeg -i "M/Monster.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Monster.mpg"
ffmpeg -i "M/Monsters Ball.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Monsters Ball.mpg"
ffmpeg -i "M/Morning Glory.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Morning Glory.mpg"
ffmpeg -i "M/Moscow Zero.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Moscow Zero.mpg"
ffmpeg -i "M/Motherhood.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Motherhood.mpg"
ffmpeg -i "M/Moulin Rouge.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Moulin Rouge.mpg"
ffmpeg -i "M/Mr and Mrs Smith.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mr and Mrs Smith.mpg"
ffmpeg -i "M/Mr. Deeds.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mr. Deeds.mpg"
ffmpeg -i "M/Mr. Mom.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mr. Mom.mpg"
ffmpeg -i "M/Mulholland Falls.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mulholland Falls.mpg"
ffmpeg -i "M/Mummy.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mummy.mpg"
ffmpeg -i "M/Munich.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Munich.mpg"
ffmpeg -i "M/Murderous Intent.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Murderous Intent.mpg"
ffmpeg -i "M/Music and Lyrics.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Music and Lyrics.mpg"
ffmpeg -i "M/Must Love Dogs.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Must Love Dogs.mpg"
ffmpeg -i "M/My Big Fat Greek Wedding.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/My Big Fat Greek Wedding.mpg"
ffmpeg -i "M/Mystery Train.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mystery Train.mpg"
ffmpeg -i "M/Mystic River.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/M/Mystic River.mpg"
ffmpeg -i "N/Natural Born Killeres.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/N/Natural Born Killeres.mpg"
ffmpeg -i "N/New Daughter.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/N/New Daughter.mpg"
ffmpeg -i "N/New York Minute.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/N/New York Minute.mpg"
ffmpeg -i "N/Next Friday.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/N/Next Friday.mpg"
ffmpeg -i "N/Nick and Noras Infinite Playlist.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/N/Nick and Noras Infinite Playlist.mpg"
ffmpeg -i "N/Night Listener.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/N/Night Listener.mpg"
ffmpeg -i "N/No Strings Attached.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/N/No Strings Attached.mpg"
ffmpeg -i "N/Notebook.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/N/Notebook.mpg"
ffmpeg -i "N/Notorious Bettie Paige.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/N/Notorious Bettie Paige.mpg"
ffmpeg -i "N/Number 23.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/N/Number 23.mpg"
ffmpeg -i "O/On Golden Pond.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/O/On Golden Pond.mpg"
ffmpeg -i "O/Once Upon a Crime.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/O/Once Upon a Crime.mpg"
ffmpeg -i "O/One Hour Photo.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/O/One Hour Photo.mpg"
ffmpeg -i "O/Other.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/O/Other.mpg"
ffmpeg -i "O/Outsiders.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/O/Outsiders.mpg"
ffmpeg -i "O/Oxford Murders.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/O/Oxford Murders.mpg"
ffmpeg -i "P/Paper Heart.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Paper Heart.mpg"
ffmpeg -i "P/Paranormal Activity 3.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Paranormal Activity 3.mpg"
ffmpeg -i "P/Passengers.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Passengers.mpg"
ffmpeg -i "P/Paul.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Paul.mpg"
ffmpeg -i "P/Pay It Forward.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Pay It Forward.mpg"
ffmpeg -i "P/Penelope.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Penelope.mpg"
ffmpeg -i "P/Perfect Getaway.m4v"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Perfect Getaway.m4v"
ffmpeg -i "P/Phantasm.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Phantasm.mpg"
ffmpeg -i "P/Pink Panther - Steve Martin.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Pink Panther - Steve Martin.mpg"
ffmpeg -i "P/Powderpuff Girls.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Powderpuff Girls.mpg"
ffmpeg -i "P/Precious.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Precious.mpg"
ffmpeg -i "P/Prince N Me.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Prince N Me.mpg"
ffmpeg -i "P/Prince of Egypt.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Prince of Egypt.mpg"
ffmpeg -i "P/Princess of Theives.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Princess of Theives.mpg"
ffmpeg -i "P/Prom Night.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Prom Night.mpg"
ffmpeg -i "P/Proof.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Proof.mpg"
ffmpeg -i "P/Public Enemies.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Public Enemies.mpg"
ffmpeg -i "P/Punch Drunk Love.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/P/Punch Drunk Love.mpg"
ffmpeg -i "Q/Quiz Show.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/Q/Quiz Show.mpg"
ffmpeg -i "R/Rachel Getting Married.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Rachel Getting Married.mpg"
ffmpeg -i "R/Raise Your Voice.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Raise Your Voice.mpg"
ffmpeg -i "R/Raw.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Raw.mpg"
ffmpeg -i "R/Ray.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Ray.mpg"
ffmpeg -i "R/Real Steel.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Real Steel.mpg"
ffmpeg -i "R/Reality Bites.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Reality Bites.mpg"
ffmpeg -i "R/Red Dawn.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Red Dawn.mpg"
ffmpeg -i "R/Red.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Red.mpg"
ffmpeg -i "R/Reign Over Me.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Reign Over Me.mpg"
ffmpeg -i "R/Remember the Titans.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Remember the Titans.mpg"
ffmpeg -i "R/Reno 911.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Reno 911.mpg"
ffmpeg -i "R/Revolver.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Revolver.mpg"
ffmpeg -i "R/Rhapsody in August.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Rhapsody in August.mpg"
ffmpeg -i "R/Ring 2.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Ring 2.mpg"
ffmpeg -i "R/Ring.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Ring.mpg"
ffmpeg -i "R/Ringer.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Ringer.mpg"
ffmpeg -i "R/Rio.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Rio.mpg"
ffmpeg -i "R/Rise of the Planet of the Apes.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Rise of the Planet of the Apes.mpg"
ffmpeg -i "R/Road to Perdition.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Road to Perdition.mpg"
ffmpeg -i "R/Rookie.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Rookie.mpg"
ffmpeg -i "R/Room 6.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Room 6.mpg"
ffmpeg -i "R/Roommate.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Roommate.mpg"
ffmpeg -i "R/Rumble Fish.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Rumble Fish.mpg"
ffmpeg -i "R/Rumor Has It.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Rumor Has It.mpg"
ffmpeg -i "R/Runaways.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Runaways.mpg"
ffmpeg -i "R/Rundown.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Rundown.mpg"
ffmpeg -i "R/Running with Scissors.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/Running with Scissors.mpg"
ffmpeg -i "R/RV.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/R/RV.mpg"
ffmpeg -i "S/S Darko.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/S Darko.mpg"
ffmpeg -i "S/Saved.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Saved.mpg"
ffmpeg -i "S/Saving Private Ryan.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Saving Private Ryan.mpg"
ffmpeg -i "S/School Of Rock.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/School Of Rock.mpg"
ffmpeg -i "S/Season Of The Witch.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Season Of The Witch.mpg"
ffmpeg -i "S/Secret Life Of Bees.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Secret Life Of Bees.mpg"
ffmpeg -i "S/Seeker.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Seeker.mpg"
ffmpeg -i "S/Seitch.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Seitch.mpg"
ffmpeg -i "S/Serendipity.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Serendipity.mpg"
ffmpeg -i "S/Serious Moonlight.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Serious Moonlight.mpg"
ffmpeg -i "S/Seven Samurai.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Seven Samurai.mpg"
ffmpeg -i "S/Seventh Sign.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Seventh Sign.mpg"
ffmpeg -i "S/Shaggy Dog.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Shaggy Dog.mpg"
ffmpeg -i "S/Sherrybaby.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Sherrybaby.mpg"
ffmpeg -i "S/Shes The Man.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Shes The Man.mpg"
ffmpeg -i "S/Shogun Assassin.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Shogun Assassin.mpg"
ffmpeg -i "S/Sideways.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Sideways.mpg"
ffmpeg -i "S/Signs.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Signs.mpg"
ffmpeg -i "S/Silencers.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Silencers.mpg"
ffmpeg -i "S/Slapshot.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Slapshot.mpg"
ffmpeg -i "S/Sleepers.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Sleepers.mpg"
ffmpeg -i "S/Sleepless In Seattle.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Sleepless In Seattle.mpg"
ffmpeg -i "S/Slingshot.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Slingshot.mpg"
ffmpeg -i "S/Slumdog Millionaire.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Slumdog Millionaire.mpg"
ffmpeg -i "S/Smokey And The Bandit.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Smokey And The Bandit.mpg"
ffmpeg -i "S/Smokin Aces.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Smokin Aces.mpg"
ffmpeg -i "S/Smother.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Smother.mpg"
ffmpeg -i "S/Something Borrowed.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Something Borrowed.mpg"
ffmpeg -i "S/Something Gotta Give.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Something Gotta Give.mpg"
ffmpeg -i "S/Something To Talk About.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Something To Talk About.mpg"
ffmpeg -i "S/Source Code.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Source Code.mpg"
ffmpeg -i "S/Spanglish.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Spanglish.mpg"
ffmpeg -i "S/Speed Racer.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Speed Racer.mpg"
ffmpeg -i "S/Speed.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Speed.mpg"
ffmpeg -i "S/Spiderwick.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Spiderwick.mpg"
ffmpeg -i "S/Splice.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Splice.mpg"
ffmpeg -i "S/Spongebob The Movie.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Spongebob The Movie.mpg"
ffmpeg -i "S/Spy Next Door.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Spy Next Door.mpg"
ffmpeg -i "S/Stardust.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Stardust.mpg"
ffmpeg -i "S/Stargate Part1.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Stargate Part1.mpg"
ffmpeg -i "S/Stargate Part2.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Stargate Part2.mpg"
ffmpeg -i "S/Station Agent.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Station Agent.mpg"
ffmpeg -i "S/Stealing Sinatra.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Stealing Sinatra.mpg"
ffmpeg -i "S/Step Brothers.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Step Brothers.mpg"
ffmpeg -i "S/Step Up.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Step Up.mpg"
ffmpeg -i "S/Stepfather.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Stepfather.mpg"
ffmpeg -i "S/Stepmom.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Stepmom.mpg"
ffmpeg -i "S/Stomp The Yard.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Stomp The Yard.mpg"
ffmpeg -i "S/Strange Brew.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Strange Brew.mpg"
ffmpeg -i "S/Stuck On You.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Stuck On You.mpg"
ffmpeg -i "S/Stuck.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Stuck.mpg"
ffmpeg -i "S/Super Size Me.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Super Size Me.mpg"
ffmpeg -i "S/Super.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Super.mpg"
ffmpeg -i "S/Superstar.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Superstar.mpg"
ffmpeg -i "S/Surfs Up.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Surfs Up.mpg"
ffmpeg -i "S/Surrogates.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Surrogates.mpg"
ffmpeg -i "S/Surveillance.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Surveillance.mpg"
ffmpeg -i "S/Sweet November.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Sweet November.mpg"
ffmpeg -i "S/Sydney White.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/S/Sydney White.mpg"
ffmpeg -i "T/Take Me Home Tonight.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Take Me Home Tonight.mpg"
ffmpeg -i "T/Taking Lives.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Taking Lives.mpg"
ffmpeg -i "T/Talladega Nights.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Talladega Nights.mpg"
ffmpeg -i "T/Tangled.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Tangled.mpg"
ffmpeg -i "T/Taxi.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Taxi.mpg"
ffmpeg -i "T/Tenure.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Tenure.mpg"
ffmpeg -i "T/Terminal.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Terminal.mpg"
ffmpeg -i "T/Texas Chainsaw Massacre.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Texas Chainsaw Massacre.mpg"
ffmpeg -i "T/The Tourist.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/The Tourist.mpg"
ffmpeg -i "T/Thelma And Louise.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Thelma And Louise.mpg"
ffmpeg -i "T/They.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/They.mpg"
ffmpeg -i "T/Thing.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Thing.mpg"
ffmpeg -i "T/Three Burials.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Three Burials.mpg"
ffmpeg -i "T/Tideland.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Tideland.mpg"
ffmpeg -i "T/Time Travelers Wife.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Time Travelers Wife.mpg"
ffmpeg -i "T/Tin Men.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Tin Men.mpg"
ffmpeg -i "T/Tolkien Ntsc Scn.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Tolkien Ntsc Scn.mpg"
ffmpeg -i "T/Transsiberian.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Transsiberian.mpg"
ffmpeg -i "T/Trapped In Paradise.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Trapped In Paradise.mpg"
ffmpeg -i "T/Traveler.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Traveler.mpg"
ffmpeg -i "T/Tropic Thunder.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Tropic Thunder.mpg"
ffmpeg -i "T/Troy.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Troy.mpg"
ffmpeg -i "T/True Grit.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/True Grit.mpg"
ffmpeg -i "T/Twelve.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Twelve.mpg"
ffmpeg -i "T/Twister.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Twister.mpg"
ffmpeg -i "T/Two Weeks Notice.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/T/Two Weeks Notice.mpg"
ffmpeg -i "U/Ugly.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/U/Ugly.mpg"
ffmpeg -i "U/Unaccompanied Minors.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/U/Unaccompanied Minors.mpg"
ffmpeg -i "U/Unbreakable.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/U/Unbreakable.mpg"
ffmpeg -i "U/Under Wraps.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/U/Under Wraps.mpg"
ffmpeg -i "U/Unforgettable.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/U/Unforgettable.mpg"
ffmpeg -i "U/Unhappily Ever After.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/U/Unhappily Ever After.mpg"
ffmpeg -i "U/Untouchables.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/U/Untouchables.mpg"
ffmpeg -i "V/Vacancy.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/V/Vacancy.mpg"
ffmpeg -i "V/Valentines Day.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/V/Valentines Day.mpg"
ffmpeg -i "V/Valkyrie.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/V/Valkyrie.mpg"
ffmpeg -i "V/Vantage Point.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/V/Vantage Point.mpg"
ffmpeg -i "V/Village.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/V/Village.mpg"
ffmpeg -i "V/Vow.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/V/Vow.mpg"
ffmpeg -i "W/Waiting For Guffman.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Waiting For Guffman.mpg"
ffmpeg -i "W/Wanted.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Wanted.mpg"
ffmpeg -i "W/War Inc.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/War Inc.mpg"
ffmpeg -i "W/We.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/We.mpg"
ffmpeg -i "W/Wedding Planner.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Wedding Planner.mpg"
ffmpeg -i "W/Wedding Singer.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Wedding Singer.mpg"
ffmpeg -i "W/Welcome To Mooseport169.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Welcome To Mooseport169.mpg"
ffmpeg -i "W/Westworld.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Westworld.mpg"
ffmpeg -i "W/What To Expect When Youre Expecting.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/What To Expect When Youre Expecting.mpg"
ffmpeg -i "W/Whats Up Tiger Lily.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Whats Up Tiger Lily.mpg"
ffmpeg -i "W/When A Man Loves A Woman.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/When A Man Loves A Woman.mpg"
ffmpeg -i "W/When In Rome.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/When In Rome.mpg"
ffmpeg -i "W/Whip It.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Whip It.mpg"
ffmpeg -i "W/White Chicks.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/White Chicks.mpg"
ffmpeg -i "W/Whiteout.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Whiteout.mpg"
ffmpeg -i "W/Who Framed Roger Rabbit.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Who Framed Roger Rabbit.mpg"
ffmpeg -i "W/Whole Nine Yards.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Whole Nine Yards.mpg"
ffmpeg -i "W/Wicker Man.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Wicker Man.mpg"
ffmpeg -i "W/Wild Child.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Wild Child.mpg"
ffmpeg -i "W/Wild Hogs.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Wild Hogs.mpg"
ffmpeg -i "W/Win A Date With Tad Hamilton.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Win A Date With Tad Hamilton.mpg"
ffmpeg -i "W/Winters Bone.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Winters Bone.mpg"
ffmpeg -i "W/World Trade Center.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/World Trade Center.mpg"
ffmpeg -i "W/Worlds Fastest Indian.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Worlds Fastest Indian.mpg"
ffmpeg -i "W/Worlds Greatest Dad.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Worlds Greatest Dad.mpg"
ffmpeg -i "W/Wrecked.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/W/Wrecked.mpg"
ffmpeg -i "Y/Yes Man.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/Y/Yes Man.mpg"
ffmpeg -i "Y/You Me And Dupree.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/Y/You Me And Dupree.mpg"
ffmpeg -i "Y/Yours Mine and Ours.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/Y/Yours Mine and Ours.mpg"
ffmpeg -i "Y/Youth In Revolt.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/Y/Youth In Revolt.mpg"
ffmpeg -i "Y/Youve Got Mail.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/Y/Youve Got Mail.mpg"
ffmpeg -i "Z/Zack and Miri Make a Porno.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/Z/Zack and Miri Make a Porno.mpg"
ffmpeg -i "Z/Zombieland.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/Z/Zombieland.mpg"
ffmpeg -i "Z/Zoom.mpg"  -vcodec mpeg4 -b 3000k -acodec copy  "./reencode/Z/Zoom.mpg"
