cp -rnv SED/jazz 4TBext/
cp -rnv SED/classical 4TBext/
cp -rnv SED/opera 4TBext/
cp -rnv SED/audible 4TBext/
cp -rnv SED/moz 4TBext/
cp -rnv SED/music 4TBext/
cp -rnv SED/music-tracks 4TBext/
cp -rnv SED/music-videos 4TBext/
cp -rnv SED/calibre 4TBext/
cp -rnv SED/opera-isos 4TBext/
